---
title: "585Lab3"
author: "Goode, Jeppson, Papio"
date: "February 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(purrr)
```


First step, read in the files. 


```{r}
file1 <- lapply(excel_sheets("spreadsheets/FileOne.xlsx"), read_excel, path = "spreadsheets/FileOne.xlsx")
file2 <- lapply(excel_sheets("spreadsheets/FileTwo.xlsx"), read_excel, path = "spreadsheets/FileTwo.xlsx")

```

Before we can combine the files, or even the semesters, we need to do a little bit of cleaning.

```{r }
# First up, file 1:

file1[[1]]
# file 1 sem 1 is missing column titles
names(file1[[1]])[c(1,2)]<-c("ID", "Test")
file1[[1]] <- file1[[1]] %>% mutate ( ID= ID %% 10000, Sem =1)


file1[[2]]
# file 1 sem 2 is also missing column titles
names(file1[[2]])[c(1,2)]<-c("ID", "Test")
# delete extra column of NA's
file1[[2]] <- file1[[2]][,-15]
file1[[2]] <- file1[[2]] %>% mutate ( ID= ID %% 20000, Sem = 2)

file1[[3]]
# file 1 sem 3 is also missing column titles
names(file1[[3]])[c(1,2)]<-c("ID", "Test")
file1[[3]] <- file1[[3]] %>% mutate ( ID= ID %% 30000, Sem =3)

file1[[4]]
# file 1 sem 4 is also missing column titles
names(file1[[4]])[c(1,2)]<-c("ID", "Test")
# the ids for sem 4 have an extra 100 in them?
file1[[4]] <- file1[[4]] %>% mutate ( ID= (ID -100) %% 40000, Sem =4)

# combine the list of data frames into one dataframe
f1 <- do.call("rbind", file1)

# make sure all "test" resposes are the same case
f1$Test <- gsub("PRE", "Pre", f1$Test)
f1$Test <- gsub("POST", "post", f1$Test)
f1



```

```{r }
# Next up, file 2:

file2[[1]]
# file 1 sem 1 is missing column titles
names(file2[[1]])[c(1,2)]<-c("ID", "Test")
file2[[1]] <- file2[[1]] %>% mutate (Sem =1)


file2[[2]]
# file 2 sem 2 is also missing column titles
names(file2[[2]])[c(1,2)]<-c("ID", "Test")
file2[[2]] <- file2[[2]] %>% mutate ( ID= ID %% 20000, Sem =2)

file2[[3]]
# file 2 sem 3 is also missing column titles
names(file2[[3]])[c(1,2)]<-c("ID", "Test")
file2[[3]] <- file2[[3]] %>% mutate ( ID= ID %% 30000, Sem =3)

file2[[4]]
# file 1 sem 4 is also missing column titles
names(file2[[4]])[c(1,2)]<-c("ID", "Test")
# the ids for sem 4 have an extra 1100 in them?
file2[[4]] <- file2[[4]] %>% mutate ( ID= (ID -1100) %% 40000, Sem =4)

# looking back throu the dimensions of all 4 semesters, semester one is missing the column "MTH 3", so we'll add in a column of NAS
file2[[1]] <- file2[[1]] %>% mutate ("MTH 3" = NA)
#but I would like the columns to still be in the same order, so I will rearrange them
file2[[1]]  <- file2[[1]][,c(1:16,41,17:40)]

# combine the list of data frames into one dataframe
f2 <- do.call("rbind", file2)

# make sure all "test" resposes are the same case
f2$Test <- gsub("PRE", "Pre", f2$Test)
f2$Test <- gsub("POST", "post", f2$Test)
f2



```
